#@TYPE: Machine
#@NAME: Qualcomm Kaanapali Development Kit
#@DESCRIPTION: Machine configuration for Qualcomm Kaanapali development Kit

require conf/machine/include/qcom-kaanapali.inc

MACHINE_FEATURES = "efi usbhost usbgadget alsa wifi bluetooth"

QCOM_DTB_DEFAULT ?= "kaanapali-mtp"

KERNEL_DEVICETREE ?= " \
                      qcom/kaanapali-mtp.dtb \
                      "

QCOM_BOOT_FILES_SUBDIR = "sm8850"
QCOM_PARTITION_FILES_SUBDIR = "partitions/kaanapali-mtp"
